version: '3.8'
services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "8001:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
      REFRESH_TOKEN: ${REFRESH_TOKEN}
